/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'ihoneymon' at '13. 10. 12 오후 9:26' with Gradle 1.8
 *
 * @author ihoneymon, @date 13. 10. 12 오후 9:26
 */
public class Library {
    public static void main(String[] args) {
        System.out.println("Hello world, " + args[0]);
    }

    public boolean someLibraryMethod() {
        return true;
    }
    
    public int add(int first, int second) {
        return first + second;
    }
}
