import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'ihoneymon' at '13. 10. 12 오후 10:17' with Gradle 1.8
 *
 * @author ihoneymon, @date 13. 10. 12 오후 10:17
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
